### ISSUE TITLE
onchange with None should be documented as a valid use case

### ISSUE THREAD

**Issue by grayaii** [ryanjjung/retemplate#8]
I see here:
https://github.com/ryanjjung/retemplate/blob/master/retemplate/__init__.py#L431
"# Why would someone not set an onchange command? I dunno, but we should handle it gracefully"

The use case is if there is a cron file (ie /etc/cron.d/foo) that we need to templatize.
Nothing needs to be executed when the cron file is changed.

The next time cron runs, it will pick up the change automatically.

**Comment by ryanjjung** [comment]
https://github.com/ryanjjung/retemplate/pull/10
