### ISSUE TITLE
allow default value, if value is not present

### ISSUE THREAD

**Issue by grayaii** [ryanjjung/retemplate#9]
It would be awesome if defaults were applicable.  Perphaps something like this:
{< my-secret-val = rtpl://secrets-manager/my-super-secret, "good-value-default" >}

This will allow us to do something like this:

{< env = rtpl://metadata?arg=ec2_tags/environment >}
{< default_val = rtpl://secrets-manager/default.loggly_lower_envs.api_key >}
{< key = rtpl://secrets-manager/{<env>}.loggly.api_key, {<default_val>}>}

Since the secret for {<env>}.loggly.api_key has not been created yet, it would make sense to use a sane default value.

**Comment by ryanjjung** [comment]
How about making the default be an unmistakable optional argument in the URL, like this?

    rtpl://store/key?rtpl_default=blah

**Comment by grayaii** [comment]
Perfect!

**Comment by ryanjjung** [comment]
https://github.com/ryanjjung/retemplate/pull/12

**Comment by ryanjjung** [comment]
New version 0.0.11 has been pushed to PyPi with this feature.
